//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace dal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rehabilitation_management_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rehabilitation_management_dbEntities object using the connection string found in the 'rehabilitation_management_dbEntities' section of the application configuration file.
        /// </summary>
        public rehabilitation_management_dbEntities() : base("name=rehabilitation_management_dbEntities", "rehabilitation_management_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rehabilitation_management_dbEntities object.
        /// </summary>
        public rehabilitation_management_dbEntities(string connectionString) : base(connectionString, "rehabilitation_management_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rehabilitation_management_dbEntities object.
        /// </summary>
        public rehabilitation_management_dbEntities(EntityConnection connection) : base(connection, "rehabilitation_management_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_clients> tbl_clients
        {
            get
            {
                if ((_tbl_clients == null))
                {
                    _tbl_clients = base.CreateObjectSet<tbl_clients>("tbl_clients");
                }
                return _tbl_clients;
            }
        }
        private ObjectSet<tbl_clients> _tbl_clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_institutions> tbl_institutions
        {
            get
            {
                if ((_tbl_institutions == null))
                {
                    _tbl_institutions = base.CreateObjectSet<tbl_institutions>("tbl_institutions");
                }
                return _tbl_institutions;
            }
        }
        private ObjectSet<tbl_institutions> _tbl_institutions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_AllowedReportsRolesMenus> tbl_AllowedReportsRolesMenus
        {
            get
            {
                if ((_tbl_AllowedReportsRolesMenus == null))
                {
                    _tbl_AllowedReportsRolesMenus = base.CreateObjectSet<tbl_AllowedReportsRolesMenus>("tbl_AllowedReportsRolesMenus");
                }
                return _tbl_AllowedReportsRolesMenus;
            }
        }
        private ObjectSet<tbl_AllowedReportsRolesMenus> _tbl_AllowedReportsRolesMenus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_AllowedRoleMenus> tbl_AllowedRoleMenus
        {
            get
            {
                if ((_tbl_AllowedRoleMenus == null))
                {
                    _tbl_AllowedRoleMenus = base.CreateObjectSet<tbl_AllowedRoleMenus>("tbl_AllowedRoleMenus");
                }
                return _tbl_AllowedRoleMenus;
            }
        }
        private ObjectSet<tbl_AllowedRoleMenus> _tbl_AllowedRoleMenus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_MenuItems> tbl_MenuItems
        {
            get
            {
                if ((_tbl_MenuItems == null))
                {
                    _tbl_MenuItems = base.CreateObjectSet<tbl_MenuItems>("tbl_MenuItems");
                }
                return _tbl_MenuItems;
            }
        }
        private ObjectSet<tbl_MenuItems> _tbl_MenuItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Menus> tbl_Menus
        {
            get
            {
                if ((_tbl_Menus == null))
                {
                    _tbl_Menus = base.CreateObjectSet<tbl_Menus>("tbl_Menus");
                }
                return _tbl_Menus;
            }
        }
        private ObjectSet<tbl_Menus> _tbl_Menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ReportsMenuItems> tbl_ReportsMenuItems
        {
            get
            {
                if ((_tbl_ReportsMenuItems == null))
                {
                    _tbl_ReportsMenuItems = base.CreateObjectSet<tbl_ReportsMenuItems>("tbl_ReportsMenuItems");
                }
                return _tbl_ReportsMenuItems;
            }
        }
        private ObjectSet<tbl_ReportsMenuItems> _tbl_ReportsMenuItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_roles> tbl_roles
        {
            get
            {
                if ((_tbl_roles == null))
                {
                    _tbl_roles = base.CreateObjectSet<tbl_roles>("tbl_roles");
                }
                return _tbl_roles;
            }
        }
        private ObjectSet<tbl_roles> _tbl_roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_users> tbl_users
        {
            get
            {
                if ((_tbl_users == null))
                {
                    _tbl_users = base.CreateObjectSet<tbl_users>("tbl_users");
                }
                return _tbl_users;
            }
        }
        private ObjectSet<tbl_users> _tbl_users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_clients(tbl_clients tbl_clients)
        {
            base.AddObject("tbl_clients", tbl_clients);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_institutions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_institutions(tbl_institutions tbl_institutions)
        {
            base.AddObject("tbl_institutions", tbl_institutions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_AllowedReportsRolesMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_AllowedReportsRolesMenus(tbl_AllowedReportsRolesMenus tbl_AllowedReportsRolesMenus)
        {
            base.AddObject("tbl_AllowedReportsRolesMenus", tbl_AllowedReportsRolesMenus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_AllowedRoleMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_AllowedRoleMenus(tbl_AllowedRoleMenus tbl_AllowedRoleMenus)
        {
            base.AddObject("tbl_AllowedRoleMenus", tbl_AllowedRoleMenus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_MenuItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_MenuItems(tbl_MenuItems tbl_MenuItems)
        {
            base.AddObject("tbl_MenuItems", tbl_MenuItems);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Menus(tbl_Menus tbl_Menus)
        {
            base.AddObject("tbl_Menus", tbl_Menus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ReportsMenuItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ReportsMenuItems(tbl_ReportsMenuItems tbl_ReportsMenuItems)
        {
            base.AddObject("tbl_ReportsMenuItems", tbl_ReportsMenuItems);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_roles(tbl_roles tbl_roles)
        {
            base.AddObject("tbl_roles", tbl_roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_users(tbl_users tbl_users)
        {
            base.AddObject("tbl_users", tbl_users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_AllowedReportsRolesMenus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_AllowedReportsRolesMenus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_AllowedReportsRolesMenus object.
        /// </summary>
        /// <param name="allowed_report_role_menu_Id">Initial value of the allowed_report_role_menu_Id property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="menuItemId">Initial value of the MenuItemId property.</param>
        /// <param name="allowed">Initial value of the Allowed property.</param>
        public static tbl_AllowedReportsRolesMenus Createtbl_AllowedReportsRolesMenus(global::System.Int32 allowed_report_role_menu_Id, global::System.Int32 roleId, global::System.Int32 menuItemId, global::System.Boolean allowed)
        {
            tbl_AllowedReportsRolesMenus tbl_AllowedReportsRolesMenus = new tbl_AllowedReportsRolesMenus();
            tbl_AllowedReportsRolesMenus.allowed_report_role_menu_Id = allowed_report_role_menu_Id;
            tbl_AllowedReportsRolesMenus.RoleId = roleId;
            tbl_AllowedReportsRolesMenus.MenuItemId = menuItemId;
            tbl_AllowedReportsRolesMenus.Allowed = allowed;
            return tbl_AllowedReportsRolesMenus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 allowed_report_role_menu_Id
        {
            get
            {
                return _allowed_report_role_menu_Id;
            }
            set
            {
                if (_allowed_report_role_menu_Id != value)
                {
                    Onallowed_report_role_menu_IdChanging(value);
                    ReportPropertyChanging("allowed_report_role_menu_Id");
                    _allowed_report_role_menu_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("allowed_report_role_menu_Id");
                    Onallowed_report_role_menu_IdChanged();
                }
            }
        }
        private global::System.Int32 _allowed_report_role_menu_Id;
        partial void Onallowed_report_role_menu_IdChanging(global::System.Int32 value);
        partial void Onallowed_report_role_menu_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuItemId
        {
            get
            {
                return _MenuItemId;
            }
            set
            {
                OnMenuItemIdChanging(value);
                ReportPropertyChanging("MenuItemId");
                _MenuItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuItemId");
                OnMenuItemIdChanged();
            }
        }
        private global::System.Int32 _MenuItemId;
        partial void OnMenuItemIdChanging(global::System.Int32 value);
        partial void OnMenuItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Allowed
        {
            get
            {
                return _Allowed;
            }
            set
            {
                OnAllowedChanging(value);
                ReportPropertyChanging("Allowed");
                _Allowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Allowed");
                OnAllowedChanged();
            }
        }
        private global::System.Boolean _Allowed;
        partial void OnAllowedChanging(global::System.Boolean value);
        partial void OnAllowedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_AllowedRoleMenus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_AllowedRoleMenus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_AllowedRoleMenus object.
        /// </summary>
        /// <param name="allowed_role_menu_Id">Initial value of the allowed_role_menu_Id property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="menuItemId">Initial value of the MenuItemId property.</param>
        /// <param name="allowed">Initial value of the Allowed property.</param>
        public static tbl_AllowedRoleMenus Createtbl_AllowedRoleMenus(global::System.Int32 allowed_role_menu_Id, global::System.Int32 roleId, global::System.Int32 menuItemId, global::System.Boolean allowed)
        {
            tbl_AllowedRoleMenus tbl_AllowedRoleMenus = new tbl_AllowedRoleMenus();
            tbl_AllowedRoleMenus.allowed_role_menu_Id = allowed_role_menu_Id;
            tbl_AllowedRoleMenus.RoleId = roleId;
            tbl_AllowedRoleMenus.MenuItemId = menuItemId;
            tbl_AllowedRoleMenus.Allowed = allowed;
            return tbl_AllowedRoleMenus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 allowed_role_menu_Id
        {
            get
            {
                return _allowed_role_menu_Id;
            }
            set
            {
                if (_allowed_role_menu_Id != value)
                {
                    Onallowed_role_menu_IdChanging(value);
                    ReportPropertyChanging("allowed_role_menu_Id");
                    _allowed_role_menu_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("allowed_role_menu_Id");
                    Onallowed_role_menu_IdChanged();
                }
            }
        }
        private global::System.Int32 _allowed_role_menu_Id;
        partial void Onallowed_role_menu_IdChanging(global::System.Int32 value);
        partial void Onallowed_role_menu_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuItemId
        {
            get
            {
                return _MenuItemId;
            }
            set
            {
                OnMenuItemIdChanging(value);
                ReportPropertyChanging("MenuItemId");
                _MenuItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuItemId");
                OnMenuItemIdChanged();
            }
        }
        private global::System.Int32 _MenuItemId;
        partial void OnMenuItemIdChanging(global::System.Int32 value);
        partial void OnMenuItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Allowed
        {
            get
            {
                return _Allowed;
            }
            set
            {
                OnAllowedChanging(value);
                ReportPropertyChanging("Allowed");
                _Allowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Allowed");
                OnAllowedChanged();
            }
        }
        private global::System.Boolean _Allowed;
        partial void OnAllowedChanging(global::System.Boolean value);
        partial void OnAllowedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_clients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_clients : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_clients object.
        /// </summary>
        /// <param name="client_id">Initial value of the client_id property.</param>
        public static tbl_clients Createtbl_clients(global::System.Int32 client_id)
        {
            tbl_clients tbl_clients = new tbl_clients();
            tbl_clients.client_id = client_id;
            return tbl_clients;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 client_id
        {
            get
            {
                return _client_id;
            }
            set
            {
                if (_client_id != value)
                {
                    Onclient_idChanging(value);
                    ReportPropertyChanging("client_id");
                    _client_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("client_id");
                    Onclient_idChanged();
                }
            }
        }
        private global::System.Int32 _client_id;
        partial void Onclient_idChanging(global::System.Int32 value);
        partial void Onclient_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String client_name
        {
            get
            {
                return _client_name;
            }
            set
            {
                Onclient_nameChanging(value);
                ReportPropertyChanging("client_name");
                _client_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("client_name");
                Onclient_nameChanged();
            }
        }
        private global::System.String _client_name;
        partial void Onclient_nameChanging(global::System.String value);
        partial void Onclient_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String client_dob
        {
            get
            {
                return _client_dob;
            }
            set
            {
                Onclient_dobChanging(value);
                ReportPropertyChanging("client_dob");
                _client_dob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("client_dob");
                Onclient_dobChanged();
            }
        }
        private global::System.String _client_dob;
        partial void Onclient_dobChanging(global::System.String value);
        partial void Onclient_dobChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_institutions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_institutions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_institutions object.
        /// </summary>
        /// <param name="institution_id">Initial value of the institution_id property.</param>
        public static tbl_institutions Createtbl_institutions(global::System.Int32 institution_id)
        {
            tbl_institutions tbl_institutions = new tbl_institutions();
            tbl_institutions.institution_id = institution_id;
            return tbl_institutions;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 institution_id
        {
            get
            {
                return _institution_id;
            }
            set
            {
                if (_institution_id != value)
                {
                    Oninstitution_idChanging(value);
                    ReportPropertyChanging("institution_id");
                    _institution_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("institution_id");
                    Oninstitution_idChanged();
                }
            }
        }
        private global::System.Int32 _institution_id;
        partial void Oninstitution_idChanging(global::System.Int32 value);
        partial void Oninstitution_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String institution_name
        {
            get
            {
                return _institution_name;
            }
            set
            {
                Oninstitution_nameChanging(value);
                ReportPropertyChanging("institution_name");
                _institution_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("institution_name");
                Oninstitution_nameChanged();
            }
        }
        private global::System.String _institution_name;
        partial void Oninstitution_nameChanging(global::System.String value);
        partial void Oninstitution_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String institution_location
        {
            get
            {
                return _institution_location;
            }
            set
            {
                Oninstitution_locationChanging(value);
                ReportPropertyChanging("institution_location");
                _institution_location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("institution_location");
                Oninstitution_locationChanged();
            }
        }
        private global::System.String _institution_location;
        partial void Oninstitution_locationChanging(global::System.String value);
        partial void Oninstitution_locationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String institution_start_date
        {
            get
            {
                return _institution_start_date;
            }
            set
            {
                Oninstitution_start_dateChanging(value);
                ReportPropertyChanging("institution_start_date");
                _institution_start_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("institution_start_date");
                Oninstitution_start_dateChanged();
            }
        }
        private global::System.String _institution_start_date;
        partial void Oninstitution_start_dateChanging(global::System.String value);
        partial void Oninstitution_start_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_MenuItems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_MenuItems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_MenuItems object.
        /// </summary>
        /// <param name="menu_item_Id">Initial value of the menu_item_Id property.</param>
        /// <param name="mnuName">Initial value of the mnuName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static tbl_MenuItems Createtbl_MenuItems(global::System.Int32 menu_item_Id, global::System.String mnuName, global::System.String description)
        {
            tbl_MenuItems tbl_MenuItems = new tbl_MenuItems();
            tbl_MenuItems.menu_item_Id = menu_item_Id;
            tbl_MenuItems.mnuName = mnuName;
            tbl_MenuItems.Description = description;
            return tbl_MenuItems;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menu_item_Id
        {
            get
            {
                return _menu_item_Id;
            }
            set
            {
                if (_menu_item_Id != value)
                {
                    Onmenu_item_IdChanging(value);
                    ReportPropertyChanging("menu_item_Id");
                    _menu_item_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("menu_item_Id");
                    Onmenu_item_IdChanged();
                }
            }
        }
        private global::System.Int32 _menu_item_Id;
        partial void Onmenu_item_IdChanging(global::System.Int32 value);
        partial void Onmenu_item_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mnuName
        {
            get
            {
                return _mnuName;
            }
            set
            {
                OnmnuNameChanging(value);
                ReportPropertyChanging("mnuName");
                _mnuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mnuName");
                OnmnuNameChanged();
            }
        }
        private global::System.String _mnuName;
        partial void OnmnuNameChanging(global::System.String value);
        partial void OnmnuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_Menus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Menus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Menus object.
        /// </summary>
        /// <param name="menu_Id">Initial value of the menu_Id property.</param>
        public static tbl_Menus Createtbl_Menus(global::System.Int32 menu_Id)
        {
            tbl_Menus tbl_Menus = new tbl_Menus();
            tbl_Menus.menu_Id = menu_Id;
            return tbl_Menus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 menu_Id
        {
            get
            {
                return _menu_Id;
            }
            set
            {
                if (_menu_Id != value)
                {
                    Onmenu_IdChanging(value);
                    ReportPropertyChanging("menu_Id");
                    _menu_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("menu_Id");
                    Onmenu_IdChanged();
                }
            }
        }
        private global::System.Int32 _menu_Id;
        partial void Onmenu_IdChanging(global::System.Int32 value);
        partial void Onmenu_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mnuName
        {
            get
            {
                return _mnuName;
            }
            set
            {
                OnmnuNameChanging(value);
                ReportPropertyChanging("mnuName");
                _mnuName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mnuName");
                OnmnuNameChanged();
            }
        }
        private global::System.String _mnuName;
        partial void OnmnuNameChanging(global::System.String value);
        partial void OnmnuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_ReportsMenuItems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ReportsMenuItems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ReportsMenuItems object.
        /// </summary>
        /// <param name="report_menu_Id">Initial value of the report_menu_Id property.</param>
        /// <param name="mnuName">Initial value of the mnuName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static tbl_ReportsMenuItems Createtbl_ReportsMenuItems(global::System.Int32 report_menu_Id, global::System.String mnuName, global::System.String description)
        {
            tbl_ReportsMenuItems tbl_ReportsMenuItems = new tbl_ReportsMenuItems();
            tbl_ReportsMenuItems.report_menu_Id = report_menu_Id;
            tbl_ReportsMenuItems.mnuName = mnuName;
            tbl_ReportsMenuItems.Description = description;
            return tbl_ReportsMenuItems;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 report_menu_Id
        {
            get
            {
                return _report_menu_Id;
            }
            set
            {
                if (_report_menu_Id != value)
                {
                    Onreport_menu_IdChanging(value);
                    ReportPropertyChanging("report_menu_Id");
                    _report_menu_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("report_menu_Id");
                    Onreport_menu_IdChanged();
                }
            }
        }
        private global::System.Int32 _report_menu_Id;
        partial void Onreport_menu_IdChanging(global::System.Int32 value);
        partial void Onreport_menu_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mnuName
        {
            get
            {
                return _mnuName;
            }
            set
            {
                OnmnuNameChanging(value);
                ReportPropertyChanging("mnuName");
                _mnuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mnuName");
                OnmnuNameChanged();
            }
        }
        private global::System.String _mnuName;
        partial void OnmnuNameChanging(global::System.String value);
        partial void OnmnuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_roles object.
        /// </summary>
        /// <param name="role_id">Initial value of the role_id property.</param>
        /// <param name="shortCode">Initial value of the ShortCode property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        public static tbl_roles Createtbl_roles(global::System.Int32 role_id, global::System.String shortCode, global::System.String description, global::System.Boolean isDeleted)
        {
            tbl_roles tbl_roles = new tbl_roles();
            tbl_roles.role_id = role_id;
            tbl_roles.ShortCode = shortCode;
            tbl_roles.Description = description;
            tbl_roles.IsDeleted = isDeleted;
            return tbl_roles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 role_id
        {
            get
            {
                return _role_id;
            }
            set
            {
                if (_role_id != value)
                {
                    Onrole_idChanging(value);
                    ReportPropertyChanging("role_id");
                    _role_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("role_id");
                    Onrole_idChanged();
                }
            }
        }
        private global::System.Int32 _role_id;
        partial void Onrole_idChanging(global::System.Int32 value);
        partial void Onrole_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortCode
        {
            get
            {
                return _ShortCode;
            }
            set
            {
                OnShortCodeChanging(value);
                ReportPropertyChanging("ShortCode");
                _ShortCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortCode");
                OnShortCodeChanged();
            }
        }
        private global::System.String _ShortCode;
        partial void OnShortCodeChanging(global::System.String value);
        partial void OnShortCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Boolean _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Boolean value);
        partial void OnIsDeletedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rehabilitation_management_dbModel", Name="tbl_users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_users object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="locked">Initial value of the Locked property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        /// <param name="systemId">Initial value of the SystemId property.</param>
        public static tbl_users Createtbl_users(global::System.Int32 user_id, global::System.Int32 roleId, global::System.String userName, global::System.String password, global::System.String status, global::System.Boolean locked, global::System.Boolean isDeleted, global::System.String systemId)
        {
            tbl_users tbl_users = new tbl_users();
            tbl_users.user_id = user_id;
            tbl_users.RoleId = roleId;
            tbl_users.UserName = userName;
            tbl_users.Password = password;
            tbl_users.Status = status;
            tbl_users.Locked = locked;
            tbl_users.IsDeleted = isDeleted;
            tbl_users.SystemId = systemId;
            return tbl_users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Locked
        {
            get
            {
                return _Locked;
            }
            set
            {
                OnLockedChanging(value);
                ReportPropertyChanging("Locked");
                _Locked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Locked");
                OnLockedChanged();
            }
        }
        private global::System.Boolean _Locked;
        partial void OnLockedChanging(global::System.Boolean value);
        partial void OnLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Boolean _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Boolean value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SystemId
        {
            get
            {
                return _SystemId;
            }
            set
            {
                OnSystemIdChanging(value);
                ReportPropertyChanging("SystemId");
                _SystemId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SystemId");
                OnSystemIdChanged();
            }
        }
        private global::System.String _SystemId;
        partial void OnSystemIdChanging(global::System.String value);
        partial void OnSystemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherNames
        {
            get
            {
                return _OtherNames;
            }
            set
            {
                OnOtherNamesChanging(value);
                ReportPropertyChanging("OtherNames");
                _OtherNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherNames");
                OnOtherNamesChanged();
            }
        }
        private global::System.String _OtherNames;
        partial void OnOtherNamesChanging(global::System.String value);
        partial void OnOtherNamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NationalID
        {
            get
            {
                return _NationalID;
            }
            set
            {
                OnNationalIDChanging(value);
                ReportPropertyChanging("NationalID");
                _NationalID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NationalID");
                OnNationalIDChanged();
            }
        }
        private global::System.String _NationalID;
        partial void OnNationalIDChanging(global::System.String value);
        partial void OnNationalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateJoined
        {
            get
            {
                return _DateJoined;
            }
            set
            {
                OnDateJoinedChanging(value);
                ReportPropertyChanging("DateJoined");
                _DateJoined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateJoined");
                OnDateJoinedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateJoined;
        partial void OnDateJoinedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateJoinedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InformBy
        {
            get
            {
                return _InformBy;
            }
            set
            {
                OnInformByChanging(value);
                ReportPropertyChanging("InformBy");
                _InformBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InformBy");
                OnInformByChanged();
            }
        }
        private global::System.String _InformBy;
        partial void OnInformByChanging(global::System.String value);
        partial void OnInformByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.String _Photo;
        partial void OnPhotoChanging(global::System.String value);
        partial void OnPhotoChanged();

        #endregion

    
    }

    #endregion

    
}
